# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be3b62c2a50dcf0a72d131f98b3224f223ad22683dc624db12fb2caf86b9512148a31a80b378fa78eb5a188aeba2f809b95542ba80f7c786a6440f2e00e783cb

test:
  secret_key_base: 3af31fed15227f805ad29f8699b6a93afad6091f303de3669b93b3474466fd34dc5e8e2b18e22a459802400411d0f3493de103178f27ad1f50142d9ea4893602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
